# ==========================================
# Kitty Configuration File (Adjusted Spacing)
# ==========================================

# --- 字体配置 ---
# font_family      JetBrainsMono Nerd Font
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
font_size        10.0
confirm_os_window_close 0
# 紧凑化调整：减少行高与字间距（可根据实际视觉效果微调负值大小）
adjust_line_height  0
adjust_column_width 0

# 中文字符及常用汉字区间回退到文泉驿等宽微米黑
#symbol_map U+4E00-U+9FFF,U+3400-U+4DBF,U+20000-U+2A6DF WenQuanYi Micro Hei Mono


# --- [main] 核心配置 ---
term xterm-256color

# 窗口内边距 (上/下/左/右)
window_padding_width 3 3 1 1

# 选中文本直接复制到剪贴板
copy_on_select yes

# 双击选词时的分词符
select_by_word_characters ,│`|:"'()[]{}<>@%

# 粗体文本使用亮色
bold_text_in_bright yes


# --- [scrollback] 回滚缓冲配置 ---
scrollback_lines 1000


# --- [csd] 窗口装饰配置 ---
hide_window_decorations yes


# --- [colors-dark] 配色方案 ---
background_opacity 0.8

foreground           #f2edff
cursor               #e0e0e0
cursor_text_color    #000000

selection_background #9d8fd0
selection_foreground #1f1b33

# 常规色 (0-7)
color0 #2e3436
color1 #cc0000
color2 #4e9a06
color3 #c4a000
color4 #3465a4
color5 #75507b
color6 #06989a
color7 #d3d7cf

# 亮色 (8-15)
color8  #555753
color9  #ef2929
color10 #8ae234
color11 #fce94f
color12 #729fcf
color13 #ad7fa8
color14 #34e2e2
color15 #eeeeec


# --- [bell] 终端响铃配置 ---
enable_audio_bell no
visual_bell_duration 0.0


# --- [cursor] 光标样式配置 ---
cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval 0.5


# --- [mouse] 鼠标配置 ---
mouse_hide_wait 0


# BEGIN_KITTY_FONTS
font_family      family='Liberation Mono' postscript_name=LiberationMono
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
