[bar]
position = "top"
height = 30
background = "#1e1e2e"
foreground = "#cdd6f4"

    [bar.default]
    border = "#c4b5fd"
    border_width = 1.0
    start = ["launcher", "workspaces", "clock"]
    end = ["media", "network", "bluetooth", "volume", "battery", "tray", "session"]

[widget.clock]
format = "%H:%M:%S"

[widget.bluetooth]
enabled = true

[widget.media]
hide_when_no_media = true
title_scroll = "always"

[widget.network]
show_label = false
